name: Check github action

on: workflow_call

jobs:
  linting:
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@e6160e5a751bbcbd337a834eb75c15ba9ca206ae # v3.0.2
        with:
          aqua_version: v2.38.0
      - name: Lint github actions
        run: |
          actionlint -color
          ghalint run
