name: Release workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: node
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        if: ${{ steps.release.outputs.release_created }}
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm with pnpm install
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 9.7.0  # renovate: depName=pnpm
          run_install: true
      - run: pnpm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
