name: Release workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4.1.4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: node
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ steps.release.outputs.release_created }}
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm with pnpm install
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 9.7.0  # renovate: depName=pnpm
          run_install: true
      - run: pnpm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
